name: Bug report
description: Report a reproducible problem.
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Summary
      description: What happened?
      placeholder: Briefly describe the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: OS, browser, Node version, and any relevant setup details.
    validations:
      required: false
